### ISSUE TITLE
some questions about encoder

### ISSUE THREAD

**Issue by kuzma-long** [YChen1993/CoSeRec#3]
Hi, i want to make sure that if the Intermediate layer means FFN? If it does, then why do you want to make a feedforward fully connected LayerNorm output after doing self-attention. These two seem to be doing the same job.

**Comment by YChen1993** [comment]
> 

Hi @kuzma-long, thanks for asking. This is a variant of Transformer architecture that was proposed by GPT-2, which was shown to be more effective. You can checkout [GPT-2](https://github.com/openai/gpt-2/blob/a74da5d99abaaba920de8131d64da2862a8f213b/src/model.py#L123 ) for more details. Please feel free to close the issue if the answer is helpful. Thanks
