### ISSUE TITLE
a question about max_score and min_score in OnlineItemSimilarity

### ISSUE THREAD

**Issue by Xiuchen519** [YChen1993/CoSeRec#4]
Hi, author. Thank you for making the code public!
I find a question about max_score and min_score in OnlineItemSimilarity. The max_score and min_score is calculated in __init__()  using self.get_maximum_minimum_sim_scores(), however, max_score and min_score will be set to -1 and 100 respectively since there isn't a item_embeddings in OnlineItemSimilarity when it is initialized. And the value max_score and min_score will remain -1 and 100 in all training epoches.
In this case, the similarity will be normlized incorrectly (i.e. `sim_normlized = ((-1) - sim) / ((-1) - 100)`) and then the online similarity will become a very small value. Since the normlized online similarity is very small, item selectd from offline method will allways be used and the hybrid strategy will lose its meaning. 
The following screenshot shows the results of my debugging in the second epoch. Online similarity is much smaller than the offline similarity since it is is divided by 101.
![image](https://user-images.githubusercontent.com/54465573/178098351-67a266bc-af99-4b07-8319-bc85c73e2da2.png)
Did I miss some details in the code？Hope to get your reply.

**Comment by YChen1993** [comment]
Thanks for bringing up the question! It seems indeed a bug and I just fixed it. I will run some experiments to make sure the code works now. - Thanks
