### ISSUE TITLE
The min-max normalization may be wrong in models.py

### ISSUE THREAD

**Issue by Xiuchen519** [YChen1993/CoSeRec#6]
Hi! The min-max normalization may be wrong in `OfflineItemSimilarity` and `OnlineItemSimilarity` in models.py. I think it should be `(item_similarity - self.min_score) / (self.max_score - self.min_score)`. Did I miss some details in the code？
![image](https://user-images.githubusercontent.com/54465573/189659550-9e3f8ddb-4a0e-4db9-b0ab-1e5693465dbf.png)

**Comment by YChen1993** [comment]
@Xiuchen519 Thanks for asking! Yes, you are right. I will run some experiments to see the difference in picking the top similar or dissimilar items.

**Comment by YChen1993** [comment]
@Xiuchen519 Sounds good. I will make the updates in the next 1-2 days. Thanks!

**Comment by YChen1993** [comment]
Hi @Xiuchen519, thanks for waiting. I just updated the script and code. The result on beauty using the updated script is: 'HIT@5': '0.0491', 'NDCG@5': '0.0323', 'HIT@10': '0.0744', 'NDCG@10': '0.0404', 'HIT@20': '0.1041', 'NDCG@20': '0.0489'. I am in Python==3.7.10 and torch==1.9.0. Thanks
